### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by tyrasd** [hotosm/osm-analytics#10]
* [x] hover on number of HOT projects in stats bar
* [x] missing `x` in HOT projects modal
* [x] fix map auto-centering when manually tweaking region boundary
* [x] show currently selected date range somewhere (see mockups)
* [x] improve color scheme, e.g. choose better highlight color (not `#F00`)
* [x] …

//cc @felskia

**Comment by felskia** [comment]
To go along with a few of the notes you have above. I like the blue you chose for the highlight color. The orange stands out a bit too much though, it's so bright it feels like the color you should be paying attention to instead of the blue. My recommendation would be:

Highlighted Buildings: Light blue
Non-highlighted Buildings: Dark Blue
Roads: Orange, since the purple doesn't stand out as much right now against the blue

I've listed other small things below and added a (1) to the end of ones we think are a priority. Let me know if it would be easier breaking them out into individual tickets:

**Timeline Items**
- [ ] When there are 0 hot projects, don’t make the link clickable 
- [ ] When you zoom into the timeline, have a way to scroll back and forth (left and right) along it. (1)
- [ ] Make the title of the timeline header bold, e.g. "Recency of Edits"
- [ ] Feel as if the timeline should stop on the current day instead of going into the future. (1)
- [ ] Would prefer if each of the bars on the bar timeline was hoverable and upon hover the month and year would show up

**General Items**
- [ ] Show a spinning circle when anything is loading so that they user has some feedback. (1)
- [ ] The logo should click to about, it shouldn't be an individual link next to the map link

**Search Box Items**
- [ ] Search box has too much left padding
- [ ] Make the search icon clickable as well as hitting enter (1)
- [ ] When a region is typed into the search box and the user presses enter the term should stay in the search box until they clear the name (1)
- [ ] Show country & city suggestions when a user starts typing into the search box

**Modal Items**
- [ ] For the HOT projects modal, add the same amount of padding to the bottom of the modal as you have for the top and sides.
- [ ] For the HOT projects modal, only have the scroll bar for the projects instead of for the whole modal. This way the page header stays at the top of the page and it also will create a cleaner experience
- [ ] For the HOT projects modal, have an x in the top right hand corner of the modal so that user can edit by clicking there as well as the background.

**Comment by tyrasd** [comment]
I was able to fix almost all of your points. Thanks for spotting all the things I've missed!

I've moved into separate tickets the timebar bar hover (#19) and the search autocomplete (#20) points.

>  The logo should click to about, it shouldn't be an individual link next to the map link

You mean the title in the header? Hmm… Isn't it more common to link that to the actual *functionality*/main page instead?

> Colors

The issue with using light/dark of the same hue is that these are already in use to indicate different levels of data density at the lower-zoom levels where features are aggregated into cells. Tricky one. Let's continue this in #21
