### ISSUE TITLE
Improve error handling/feedback when OSM boundaries for places are broken

### ISSUE THREAD

**Issue by cgiovando** [hotosm/osm-analytics#39]
Trying Gampaha, Batticaloa or Mnmunai North in Sri Lanka... they used to work but now they don't. This could be because of something wrong with their boundary relation/geometry in the OSM database. The search bar function should either warn of that issue or override with another more stable boundary source.

**Comment by vdeparday** [comment]
They do work in nonimatim on www.openstreetmap.org , except the third one is Manmunai North, so it is just the typo. So I think the issue is not with the boundaries or places that are broken.

**Comment by tyrasd** [comment]
The results nominatim gives on osm.org are only POIs that have similar names to the searched administrative boundaries, e.g. the [train station](http://www.openstreetmap.org/node/2669165074) and [city center](http://www.openstreetmap.org/node/3668151968) POIs for Batticaloa. The respective admin boundaries [relation/5351721](http://www.openstreetmap.org/relation/5351721) or [relation/2918582](http://www.openstreetmap.org/relation/2918582) are "only" found by nominatim when searching for their full names *Batticaloa District* or *Manmunai North DS Division*, respectively.

This is either because of a) poor mapping in OSM (e.g. missing *short_name* and other attributes), or b) deficiencies in how nominatim searches such objects.

As I already explained in #20 there is currently no alternative for nominatim for our use case. Therefore we can't just switch to something “better” (please use that ticket to point to alternatives in case we did just miss them).

How should it be possible to detect this kind of issue in order to warn about it (and if it was possible to detect it: why wouldn't we just fix the issue for the user then?)
