### ISSUE TITLE
User names not showing when using HTTPS

### ISSUE THREAD

**Issue by tiagojsag** [hotosm/osm-analytics#75]
![image](https://user-images.githubusercontent.com/973964/29819175-dd241612-8cbf-11e7-91fa-a913e09fbaf0.png)

This is due to the fact that whosthat.osmz.ru does not have a valid https certificate

The site has no info on who's the maintainer, or how we can reach him/her.

**Comment by nerik** [comment]
@tyrasd what's the reason for not using the OSM /user endpoint directly?

**Comment by tyrasd** [comment]
> The site has no info on who's the maintainer, or how we can reach him/her.

That would be Ilya Zverev (@zverik).

> what's the reason for not using the OSM API /user endpoint directly?

I honestly don't remember anymore. Probably just because of the slightly leaner [API](https://github.com/Zverik/whosthat#api) of whosthat compared to working with the xml returned by osm's [`/user/<id>` call](https://wiki.openstreetmap.org/wiki/API_v0.6#Details_of_a_user).

**Comment by tiagojsag** [comment]
will be fixed as part of https://github.com/hotosm/osm-analytics/pull/74
